### ISSUE TITLE
로그인 및 회원가입 구현

### ISSUE THREAD

**Issue by gidskql6671** [GDSC-KNU/TIL-Backend#1]
## 목적
사용자의 로그인 및 회원가입을 구현한다.

## 요구사항 및 기능
- [x] Id, Password 기반의 로그인을 구현한다.
  - [x] User는 Account, Password, CreatedAt, Role 속성을 가진다.
  - [x] Role은 간단하게 ADMIN과 USER로 구분한다.
  - [x] 패스워드는 암호화해서 보관한다.
    - Spring Security를 사용
  - [ ] 아이디 및 패스워드 유효성 검사를 해줘야 합니다.
    - 조건은 나중에 프론트 분들이랑 같이 얘기해봐요.
  - [ ] 로그인 성공 시에 어떤 데이터 반환할지 얘기해봐야함
- [x] 인증 처리는 토큰을 사용하도록 구현한다.
  - JWT를 사용하면 될 듯 합니다.
  - Spring Security를 사용

**Comment by JiwonHwang01** [comment]
간단하게 ID, PW 기반으로 로그인, 회원가입 구현했습니다,,
